# Generated by Django 3.2.4 on 2021-06-30 04:05

import apps.files.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '파일 그룹',
                'verbose_name_plural': '파일 그룹',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=apps.files.utils.upload_to_file, verbose_name='저장된 파일 경로 (파일 업로드)')),
                ('name', models.CharField(editable=False, max_length=500, verbose_name='저장된 파일명')),
                ('origin_name', models.CharField(editable=False, max_length=500, verbose_name='원본 파일명')),
                ('file_type', models.CharField(editable=False, max_length=30, verbose_name='파일 확장자')),
                ('size', models.IntegerField(editable=False, verbose_name='파일 크기')),
                ('order', models.IntegerField(default=1, help_text='묶음 파일일 경우 적용됩니다.', null=True, verbose_name='파일 정렬 순')),
                ('file_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.filegroup', verbose_name='파일 그룹')),
            ],
            options={
                'verbose_name': '파일',
                'verbose_name_plural': '파일',
                'ordering': ['-created'],
            },
        ),
    ]
